name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"   # প্রতি ১২ ঘণ্টায় রান করবে
  workflow_dispatch:          # ম্যানুয়ালি চালানোর অপশন

jobs:
  build:
    name: generate snake gif
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: riponxd
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
